CREATE TABLE `TB_SCENARIO_NODES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SCENARIO_ID` int NOT NULL,
  `STEP_LEVEL` int NOT NULL,
  `SITUATION_TEXT` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `IMAGE_URL` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT (now()),
  PRIMARY KEY (`ID`),
  KEY `idx_scenario_step` (`SCENARIO_ID`,`STEP_LEVEL`),
  KEY `ix_TB_SCENARIO_NODES_SCENARIO_ID` (`SCENARIO_ID`),
  KEY `ix_TB_SCENARIO_NODES_ID` (`ID`),
  CONSTRAINT `TB_SCENARIO_NODES_ibfk_1` FOREIGN KEY (`SCENARIO_ID`) REFERENCES `TB_SCENARIOS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
